### ISSUE TITLE
github 构建失败

### ISSUE THREAD

**Issue by dylanZk1** [fomalhaut1998/hexo-theme-Fomalhaut#5]
/usr/local/bundle/gems/jekyll-3.9.3/lib/jekyll/theme.rb:84:in `rescue in gemspec': The butterfly theme could not be found. (Jekyll::Errors::MissingDependencyException)

/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'butterfly' (>= 0) among 146 total gem(s) (Gem::MissingSpecError)、

这个是什么原因呢？

**Comment by dujx99** [comment]
解决了吗？同问

**Comment by rabbits0209** [comment]
写的很明白主题没有找到
